__author__ = 'gkour'

REPORTING_INTERVAL = 100

# Brain Params
LEARNING_RATE = 1e-2
BATCH_SIZE = 10
CONSOLIDATION_REPLAYS = 1

# Agent Params
MOTIVATED_REWARD = 1
NON_MOTIVATED_REWARD = 0.3
MEMORY_SIZE = 10000
FORGETTING = 0.2
EXPLORATION_EPSILON = 0.2

# Environment Params
STIMULIENCODINGSIZE = 6
SUCCESS_CRITERION_THRESHOLD = 0.80
